server:
  port: 8082

spring:
  application:
    name: provider

# 用SOFARegistry做注册中心
com:
  alipay:
    sofa:
      rpc:
        registry-address: sofa://localhost:9603

service:
  unique:
    id: ds

logging:
  file:
    path: ./logs/provider
