server:
  port: 8081

spring:
  application:
    name: consumer

# 用SOFARegistry做注册中心
com:
  alipay:
    sofa:
      rpc:
        registry-address: sofa://localhost:9603
#      tracer:
#        zipkin:
#          base-url: http://localhost:9411
#      lookout:
#        agent-host-address: localhost

service:
  unique:
    id: ds

logging:
  file:
    path: ./logs/consumer
